[package]
name = "ctt-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[lib]
#name = "ctt_server"
#crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
tokio = {version = "1", features = ["full"] }
serde = {version="1", features = ["derive"] }
serde_json = "1"
async-graphql = "6"
async-graphql-axum = "6"
axum = "0.6"
chrono = {version = "0.4", features = ["serde"] }
