[package]
name = "ctt_server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Graphql api for CTT"
repository = "https://github.com/Will-Shanks/ctt_server"

[dependencies]
pyo3 = "0.19.0"
tokio = {version = "1", features = ["full"] }
serde = {version="1", features = ["derive"] }
serde_json = "1"
async-graphql = { version = "6", features = ["tracing", "chrono"] }
async-graphql-axum = "6"
axum = "0.6"
chrono = {version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
jsonwebtoken = "8"
tower = { version = "0.4", features = ["timeout"] }
tower-http = { version = "0.4", features = ["trace", "auth", "validate-request"] }
http = "0.2"
futures-util = "0.3"
http-body = "0.4"
users = "0.11"
async-trait = "0.1"
munge_auth = "0.1"
axum-server = { version = "0.5", features = ["tls-rustls"] }
lazy_static = "1"
rand = "0.8"
slack-morphism = { version = "1", features = ["axum"], optional = true}
sea-orm = { version="0.12", features = ["with-chrono", "sqlx-sqlite", "runtime-tokio-rustls", "macros"]}
sea-orm-migration = "0.12"
pbs = { path="../pbs", optional = true }

[features]
default = ["pbs", "slack"]
slack = ["slack-morphism"]
