[package]
name = "ctt_server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Graphql api for CTT"
repository = "https://github.com/Will-Shanks/ctt_server"

[dependencies]
pyo3 = "0.19.0"
tokio = {version = "1", features = ["full"] }
serde = {version="1", features = ["derive"] }
serde_json = "1"
async-graphql = { version = "6", features = ["tracing", "chrono"] }
async-graphql-axum = "6"
axum = "0.6"
chrono = {version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
