name: Gitea Actions Demo
run-name: ctt_server packaging
on: 
  push:
    branches:
      - main

jobs:
  NCAR rpm packaging:
    runs-on: host
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: update toolchain
        run: rustup update
      - name: Compile
        run: cargo build --release
      - name: Strip
        run: strip -s target/release/cttd
      - name: Build rpm
        run: cargo generate-rpm --auto-req disabled
      - name: publish to gitea
        run: curl --user shanks:${{ secrets.PACKAGING_TOKEN }} --upload-file target/generate-rpm/cttd-*.rpm https://git.hsg.ucar.edu/api/packages/shanks/rpm/upload
